#!/bin/sh
# getolddata yyyymmdd hh
cd $HOME/public_html/met/data2
date -u
d=`date -u +%Y%m%d`
python getdatanomads2.py $1 $2 || { echo gfs err;exit 1; }

cp -rp gfs.time gfs-* mov-* ..

. $HOME/public_html/met/gfs/generate_wind_data.sh
date -u
# 10.5 +   + 5
